### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zahmryan/holidayappforms#1]
It looks like the form inputs are resetting each time the form submits, while it's specified in the project criteria that `every form field should always show the current parameters`. [This example](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) may help you figure out how you can fix this problem.

Let me know when the code is updated and I'll take another look.

**Comment by zahmryan** [comment]
The form fields now hold their values after the form is submitted

**Comment by chrisvfritz** [comment]
:+1: Much better!
